---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---
```{r message=FALSE, warning=FALSE, include=FALSE}
install.packages('data.table',repos='https://cran.fiocruz.br/')
install.packages('plyr',repos='https://cran.fiocruz.br/')
install.packages('dplyr',repos='https://cran.fiocruz.br/')
install.packages('stringr',repos='https://cran.fiocruz.br/')
install.packages('ggplot2',repos='https://cran.fiocruz.br/')
install.packages('maps',repos='https://cran.fiocruz.br/')
install.packages('bit64',repos='https://cran.fiocruz.br/')
install.packages('RColorBrewer',repos='https://cran.fiocruz.br/')
install.packages('choroplethr',repos='https://cran.fiocruz.br/')
```
```{r include=FALSE}
install.packages('choroplethr',repos='https://cran.fiocruz.br/')

```


```{r include=FALSE}
library(data.table)
library(plyr)
library(dplyr)
library(stringr)
library(ggplot2)
library(maps)
library(bit64)
library(RColorBrewer)
library(choroplethr)
```

## Importing employment data into R

```{r}
ann2017 <- fread('data/2017.annual.singlefile.csv', sep=',')
```

## Exploring the employment data


```{r}
dim(ann2017)
```


```{r}
head(ann2017)
```

## Obtaining and merging additional data


```{r}
for(u in c('agglevel','area','industry','ownership','size')){
assign(u,read.csv(paste('data/',u,'_titles.csv',sep=''),stringsAsFactors=
F))
}
```

```{r}
codes <- c('agglevel','industry','ownership','size')
ann2017full <- ann2017
for(i in 1:length(codes)){
eval(parse(text=paste('ann2017full <- left_join(ann2017full, ',codes[i],')', sep='')))
}
```

## Adding geographical information

```{r}
head(area)
```

```{r}
simpleCap <-function(x){
if(!is.na(x)){
s <- strsplit(x,' ')[[1]]
paste(toupper(substring(s,1,1)), substring(s,2), sep='', collapse=' ')
} else {NA}
}
```

```{r}
data(county.fips)
head(county.fips)
```
.
```{r}
county.fips$fips <- str_pad(county.fips$fips, width=5, pad="0")
```

```{r}
county.fips$polyname <- as.character(county.fips$polyname)
county.fips$county <- sapply(
  gsub('[a-z\ ]+,([a-z\ ]+)','\\1',county.fips$polyname), simpleCap)
county.fips <- unique(county.fips)
```

```{r}
data(state.fips)
```

```{r}
state.fips$fips <- str_pad(state.fips$fips, width=2, pad="0", side='left')
state.fips$state <- as.character(state.fips$polyname)
state.fips$state <- gsub("([a-z\ ]+):[a-z\ \\']+",'\\1',state.fips$state)
state.fips$state <- sapply(state.fips$state, simpleCap)
```

```{r}
mystatefips <-unique(state.fips[,c('fips','abb','state')])
```

```{r}
lower48 <- setdiff(unique(state.fips$state),c('Hawaii','Alaska'))
```

```{r}
myarea <- merge(area, county.fips, by.x='area_fips', by.y='fips', all.x=T)
myarea$state_fips <- substr(myarea$area_fips, 1,2)
myarea <- merge(myarea, mystatefips,by.x='state_fips',by.y='fips', all.x=T)
```

```{r}
ann2017full <- left_join(ann2017full, myarea)
ann2017full <- filter(ann2017full, state %in% lower48)
```

```{r}
save(ann2017full, file='data/ann2017full.rda',compress=T)
```

```{r}
head(ann2017full)
```

## Extracting state- and county-level wage and employment information

```{r}
d.state <- filter(ann2017full, agglvl_code==50)
d.state <- select(d.state, state, avg_annual_pay, annual_avg_emplvl)
```

```{r}
d.state$wage <- cut(d.state$avg_annual_pay, 
quantile(d.state$avg_annual_pay, c(seq(0,.8, by=.2), .9, .95, .99, 1)))
d.state$empquantile <- cut(d.state$annual_avg_emplvl, 
 quantile(d.state$annual_avg_emplvl, c(seq(0,.8,by=.2),.9,.95,.99,1)))
```

```{r}
x <- quantile(d.state$avg_annual_pay, c(seq(0,.8,by=.2),.9, .95, .99, 1))
xx <- paste(round(x/1000),'K',sep='')
Labs <- paste(xx[-length(xx)],xx[-1],sep='-')
levels(d.state$wage) <- Labs

x <- quantile(d.state$annual_avg_emplvl, c(seq(0,.8,by=.2),.9, .95, .99, 1))
xx <- ifelse(x>1000, paste(round(x/1000),'K',sep=''),round(x))
Labs <- paste(xx[-length(xx)],xx[-1],sep='-')
levels(d.state$empquantile) <- Labs
```

```{r}
Discretize <- function(x, breaks=NULL){
if(is.null(breaks)){
    breaks <- quantile(x, c(seq(0,.8,by=.2),.9, .95, .99, 1))
    if (sum(breaks==0)>1) { 
      temp <- which(breaks==0, arr.ind=TRUE)
      breaks <- breaks[max(temp):length(breaks)]
    }
  }
  x.discrete <- cut(x, breaks, include.lowest=TRUE)
  breaks.eng <- ifelse(breaks > 1000,
                       paste0(round(breaks/1000),'K'),
                       round(breaks))
  Labs <- paste(breaks.eng[-length(breaks.eng)], breaks.eng[-
1],
                sep='-')
  levels(x.discrete) <- Labs
  return(x.discrete)
}
```

```{r}
d.cty <- filter(ann2017full, agglvl_code==70) %>% select(state,county,abb, avg_annual_pay,annual_avg_emplvl)%>%
mutate(wage=Discretize(avg_annual_pay),
empquantile=Discretize(annual_avg_emplvl))
```

## Visualizing geographical distributions of pay

```{r}
state_df <- map_data('state')
county_df <- map_data('county')
```

```{r}
transform_mapdata <- function(x){
   names(x)[5:6] <- c('state','county')
   for(u in c('state','county')){
     x[,u] <- sapply(x[,u],simpleCap)
   }
   return(x)
}
state_df <- transform_mapdata(state_df)
county_df <- transform_mapdata(county_df)
```

```{r}
chor <- left_join(state_df, d.state, by='state')
ggplot(chor, aes(long,lat,group=group))+
geom_polygon(aes(fill=wage))+geom_path(color='black',size=0.2) + scale_fill_brewer(palette='PuRd') + theme(axis.text.x=element_blank(), 
axis.text.y=element_blank(), axis.ticks.x=element_blank(), 
axis.ticks.y=element_blank())
```
```{r}
chor <- left_join(county_df, d.cty)
ggplot(chor, aes(long,lat, group=group))+
  geom_polygon(aes(fill=wage))+
  geom_path( color='white',alpha=0.5,size=0.2)+
  geom_polygon(data=state_df, color='black',fill=NA)+
  scale_fill_brewer(palette='PuRd')+
  labs(x='',y='', fill='Avg Annual Pay')+
  theme(axis.text.x=element_blank(), axis.text.y=element_blank(), axis.ticks.x=element_blank(), axis.ticks.y=element_blank())
```

## Exploring where the jobs are, by industry

```{r}
d.sectors <- filter(ann2017full, industry_code %in% c(11,21,54,52),
own_code==5, # Private sector 
agglvl_code == 74 # county-level
) %>%
select(state,county,industry_code, own_code,agglvl_code,  
      industry_title, own_title, avg_annual_pay, 
      annual_avg_emplvl)%>%
mutate(wage=Discretize(avg_annual_pay),
emplevel=Discretize(annual_avg_emplvl))
d.sectors <- filter(d.sectors, !is.na(industry_code))
```

```{r}
chor <- left_join(county_df, d.sectors)
ggplot(chor, aes(long,lat,group=group))+
  geom_polygon(aes(fill=emplevel))+
  geom_polygon(data=state_df, color='black',fill=NA)+
  scale_fill_brewer(palette='PuBu')+
  facet_wrap(~industry_title, ncol=2, as.table=T)+
  labs(fill='Avg Employment Level',x='',y='')+
  theme(axis.text.x=element_blank(), 
      axis.text.y=element_blank(),   
     axis.ticks.x=element_blank(), 
     axis.ticks.y=element_blank())
```

## Animating maps for a geospatial time series

```{r}
get_data <- function(zipfile){
  #unzip(file.path('data',zipfile), exdir='data') # unzips the file
  csvfile <- gsub('zip','csv', zipfile) # Change file name
  csvfile <- gsub('_','.',csvfile) # Change _ to . in name
  dat <- fread(file.path('data', csvfile)) # read data
  dat <- left_join(dat, myarea)
  dat <- filter(dat, agglvl_code==70) %>% # County-level aggregate
  select(state, county, avg_annual_pay) # Keep variables
  return(dat)
}
```

```{r}
#install.packages('doParallel')
```

```{r}
files <- dir('data', pattern='annual_singlefile.zip') # file names
n <- length(files)
dat_list <- vector('list',n) # Initialize the list
for(i in 1:n){
  dat_list[[i]]<- get_data(files[i])  # ingest data
  names(dat_list)[i] <- substr(files[i],1,4) #label list with years
}
```

```{r}
annpay <- ldply(dat_list) # puts all the data together
breaks <- quantile(annpay$avg_annual_pay,    
c(seq(0,.8,.2),.9,.95,.99,1)) # Makes a common set of breaks
```

```{r}
mychoro <- function(d, fill_label=''){
  # d has a variable "outcome" that 
  # is plotted as the fill measure
  chor <- left_join(county_df, d)
  plt <- ggplot(chor, aes(long,lat, group=group))+
  geom_polygon(aes(fill=outcome))+    
  geom_path(color='white',alpha=0.5,size=0.2)+
  geom_polygon(data=state_df, color='black',fill=NA)+
  scale_fill_brewer(palette='PuRd')+
  labs(x='',y='', fill=fill_label)+
  theme(axis.text.x=element_blank(), 
  axis.text.y=element_blank(), 
  axis.ticks.x=element_blank(),axis.ticks.y=element_blank())
  return(plt)
}
```

```{r}
plt_list <- vector('list',n)
for(i in 1:n){
dat_list[[i]] <- mutate(dat_list[[i]],                        
outcome=Discretize(avg_annual_pay,breaks=breaks))
plt_list[[i]] <-
mychoro(dat_list[[i]])+ggtitle(names(dat_list)[i])
}
```

```{r}
choroplethr_animate(plt_list)
```


```{r include=FALSE}
#install.packages('rbenchmark')
```

```{r include=FALSE}
#library('rbenchmark')
```

```{r include=FALSE}
#opload <- benchmark(
#  CSV=read.csv('data/2017.annual.singlefile.csv', 
#  stringsAsFactors=F),
#  CSVZIP=read.csv(unz('data/2017_annual_singlefile.zip',
#   '2017.annual.singlefile.csv'), stringsAsFactors=F),
#  LOAD = load('data/ann2017full.rda'),
#  FREAD = fread('data/2017.annual.singlefile.csv'),
#  order='relative', # Report in order from shortest to longest 
#  replications=5
#)
```
